@startuml lanzarAplicacion

actor Usuario

boundary ZListadoAplicaciones <<Component>>
boundary Index

Usuario -> ZListadoAplicaciones: lanzarAplicacion(idApl:string)
activate ZListadoAplicaciones
ZListadoAplicaciones -> Store: dispatch(zaplicacion.actions.lanzarAplicacion(idApl))
deactivate ZListadoAplicaciones


@enduml