@startuml

actor Usuario

boundary ZListadoAplicaciones <<Component>>
boundary Index
boundary ZAplicacionContainer <<Component>>

Usuario -> ZListadoAplicaciones: lanzarAplicacion(idApl:string)
ZListadoAplicaciones -> Index : cuando se carga la página
activate Index

Index -> ZUtils.Services : getQueryStringParameter('idApl')
activate ZUtils.Services
Index <-- ZUtils.Services: idApl = idApl:string
deactivate ZUtils.Services

alt idApl != undefined

note left: Obtener idApl del QueryString
Index -> Index:obtenerEstadoInicial(idApl):
activate Index
Index -> IZAplState : zAplState = new { idApl:string }
Index -> Redux: createStore(App.Reducers.zaplState, zAplState, middlewares...)
Index <-- Redux: store

deactivate Index
deactivate Index
end

@enduml